---
- name: Install packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - git
      - python3-netifaces
      - python3-pip
    state: present

- name: Clone my respondd with git
  become: yes
  git:
    repo: 'https://github.com/freifunkMUC/ext-respondd'
    dest: /opt/ext-respondd/
    force: yes

- name: Copy systemd file
  become: yes
  copy:
    remote_src: yes
    src: /opt/ext-respondd/ext-respondd.service.example
    dest: /etc/systemd/system/ext-respondd.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: reload systemd and start respondd
  become: yes
  systemd:
    name: ext-respondd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Create welt directory
  become: yes
  template:
    src: 'templates/router_info.j2'
    dest: '/opt/ext-respondd/alias.json'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Create respondd config
  become: yes
  template:
    src: 'templates/respondd.j2'
    dest: '/opt/ext-respondd/config.json'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Cronjob checking if service is up and running and restart it if needed
  become: yes
  cron:
    name: "Restart stuck ext-respondd"
    minute: "*/15"
    hour: "*"
    job: "systemctl is-active --quiet ext-respondd || systemctl restart ext-respondd"
